### PR TITLE
Fix rpm build

### PR DESCRIPTION
**Pull request by intika**
update & fix rpm build

### CODE REVIEW

**Comment by danfruehauf** [comment]
@intika What distribution are you building for?

The spec file in this repository is provided in a complimentary way. The proper spec files are available for fedora/centos and you can also grab rpms for those distributions.

**Comment by intika** [comment]
@danfruehauf iam building for opensuse/fedora/mageia ... 
i am playing with the project to see how i can use it from this repo... the build does not seem to be able to replace the current used plasma-nm-ssh rpm

**Comment by intika** [comment]
@danfruehauf now about the fix i just pr ed its to make the build command 
  'autoreconf -fvi && ./configure && make rpm' work otherwise it does not

**Comment by danfruehauf** [comment]
> now about the fix i just pr ed its to make the build command
> 'autoreconf -fvi && ./configure && make rpm' work otherwise it does not

I'll take your word that it does not. Generally, I've been thinking of removing the spec file from this repository for while, since it can cause some grief to people who are unfamiliar with compilation and packaging. The recommended way of installing it is via yum/dnf.

**Comment by intika** [comment]
> > now about the fix i just pr ed its to make the build command
> > 'autoreconf -fvi && ./configure && make rpm' work otherwise it does not
> 
> I'll take your word that it does not. Generally, I've been thinking of removing the spec file from this repository for while, since it can cause some grief to people who are unfamiliar with compilation and packaging. The recommended way of installing it is via yum/dnf.

Yes i know... 2 new built files where added over time since you last edited the spec file i just added them to the spec file nothing more, otherwise the compile process does not finish and return

```
error: Installed (but unpackaged) file(s) found:
   /usr/lib/NetworkManager/VPN/nm-ssh-service.name
   /usr/share/appdata/network-manager-ssh.metainfo.xml 
```

**Comment by danfruehauf** [comment]
I should probably also update the package for Fedora. Thanks for that!

**Pull request merged**
