### PR TITLE
Port to Gtk4

### PR DESCRIPTION
**Pull request by lkundrak**
GNOME 42 seems to be switching to Gtk4, so we seem to be in a bit of a hurry to port the VPN plugins over.

The bunch of the changes are much the same as is done for other plugins [1]. The things that are going to come up with that review are likely to affect this too. I suggest this is not merged before the OpenVPN plugin gets sorted out, so there's a good example of how to do things properly.

[1] https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/merge_requests/41

Note that due to the time constrains I have not verified if this works well; I merely got it to compile and run. Feedback and fixes are very welcome.

### CODE REVIEW

**Comment by danfruehauf** [comment]
@lkundrak Thanks heaps for doing that. I'll merge it as is - always trust your work. Hopefully I'll get to test it soon, package it for the next Fedora release...

If I don't get to it (life is always hectic) - please feel free to just merge it.

Or ping me when the openvpn plugin gets sorted out...

**Comment by nielsenb-jf** [comment]
Missing Gnome 42 support has been reported downstream[0], is there anything I can do to help get this merged into a new release in time for Fedora 36?

[0] - https://bugzilla.redhat.com/show_bug.cgi?id=2061693

**Comment by lallenlowe** [comment]
I am also happy to hop in and help so I can use this in Fedora 36. 
https://bugzilla.redhat.com/show_bug.cgi?id=2061693

**Comment by heis2201** [comment]
Just in case, you were not yet aware of it, the issue also exists for the NM-strongswan plugin. downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=2081321

**Comment by dkosovic** [comment]
I've created NetworkManager-ssh 1.2.12 Fedora 36 RPMs built with this pull request applied as a patch and put them up on a COPR repository, see :
* https://bugzilla.redhat.com/show_bug.cgi?id=2061693#c13

**Comment by amyipdev** [comment]
Bumping due to importance - `nm-connection-editor` and other proposed solutions are far less clear for SSH than the GNOME version.

**Comment by danfruehauf** [comment]
I won't have time to test it, but trusting @lkundrak knows the job better than me :)

**Pull request merged**
